### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by xXxLINKIxXx** [dimankiev/dhackos#1]
Crash bug x)

My steps:
1. Create new account
2. Type command - "load_list"
3. Get game crash ::)

![image](https://user-images.githubusercontent.com/29580493/47250896-8ba52f00-d454-11e8-8873-57049ac88bb2.png)

 - OS: Windows10
 - OS account type: Admin
 - Game version: 0.1.7.b
 - Python version: 3.7.0

:)

**Comment by dimankiev** [comment]
@xXxLINKIxXx, thanks for report, I will fix it with the next update
