### ISSUE TITLE
Duplicate addresses in load_list

### ISSUE THREAD

**Issue by xXxLINKIxXx** [dimankiev/dhackos#2]
### 🔁  Duplicate addresses in target_list 🔁

**My Steps:**
> 1. Scan targets in subnet
> 2. Check load_list(target_list)

**My expected:**
I expected that the addresses in the list will not be repeated. I think it's better to use dictionary to check if there is such a target in the list when scanning a subnet.

**Screenshot:**
![image](https://user-images.githubusercontent.com/29580493/47251125-61a23b80-d459-11e8-9d05-35fa0c681bed.png)

**Game version:** _0.1.7b_

:)

**Comment by dimankiev** [comment]
It's normal, because `load_list` and `scan` modules must show you 10 IPs always, and they need to fill all blanks until 10000th scan attempt reached
