### ISSUE TITLE
Improper handling of user input in 'upgrade'

### ISSUE THREAD

**Issue by xXxLINKIxXx** [dimankiev/dhackos#3]
### 😛 Improper handling of user input in 'upgrade' 😛

**My steps:**

> 1. Run upgrade program
> 2. Type number value

**My expected:**
_Handling erroneous input before._

**Screenshot:**
![image](https://user-images.githubusercontent.com/29580493/47251194-0e30ed00-d45b-11e8-9264-82da0def3e33.png)

**Game version:** _0.1.7b_

:)

**Comment by dimankiev** [comment]
It was normal... But ok, fixed
