### ISSUE TITLE
Balance is restarted when use LanHunt

### ISSUE THREAD

**Issue by EightNice** [dimankiev/dhackos#4]
## Bug description:
Wallet balance resets when use lanhunt feature

## Steps to reproduce the behavior:
1. Start new game
2. Check balance
3. Run "lanhunt"
4. Exit "lanhunt"
5. Check balance

When you start a new game your wallet balance is 350 ETH but the lanhunt transfer overwrite the main balance instead of add it each time you use lanhunter.

- Game version: [0.3.3b]

![IMG_20210705_211712](https://user-images.githubusercontent.com/50931675/124511572-c737e100-ddd6-11eb-9d9b-d69d4d551cd9.jpg)

**Comment by EightNice** [comment]
Adding "+" solve the bug `player["ethereums"] += lanhunt.mainLanHuntCLI()`
 I've checked when exit lanhunt without hack, the wallet balance overwrites to 0 ETH but when exit lanhunt with ETH transfer overwrites with the amount you hacked

**Comment by dimankiev** [comment]
The issue is resolved now
