### ISSUE TITLE
Current balance showed by Darknet Bank is wrong

### ISSUE THREAD

**Issue by EightNice** [dimankiev/dhackos#5]
## Bug description:
The current balance showed by darknet bank to make a deposit is different to the real current balance showed by "balance" command. So when try to make a deposit get:
```
Insufficient balance !
Deposit aborted !
```
## Steps to reproduce the behavior:
1. Check the balance
2. Get into the bank
3. Check current balance showed when try to make a deposit

- Game version: [0.3.3b]

![IMG_20210705_215522](https://user-images.githubusercontent.com/50931675/124514411-3dd7dd00-dddd-11eb-855a-2c0d9975248d.jpg)

**Comment by EightNice** [comment]
Need to check when this bug occurs because in my last session it seemed to work well

**Comment by dimankiev** [comment]
There is other problem: Your wallet balance in the bank is rounded, while the balance in ETH Wallet program is not rounded
