### ISSUE TITLE
Update_ip does not work

### ISSUE THREAD

**Issue by EightNice** [dimankiev/dhackos#7]
### **Bug description:**

When try to change IP make the process but not change in prompt

### **Steps to reproduce the behavior:**

1. Run command `update_ip` some times in a row
2. Look for not changed IP in prompt

![IMG_20210706_061603](https://user-images.githubusercontent.com/50931675/124541516-df811d80-de21-11eb-9f53-4a3ed6c886ca.jpg)

- Game version: [0.3.3b]
- Python versión: [3.9.6]

**Comment by dimankiev** [comment]
#9 Fixed the issue
